### ISSUE TITLE
JSONStringer should allow to *not* render null-value properties

### ISSUE THREAD

**Issue by sebfz1** [openjson/openjson#7]
Hi,

I'd like to render json object without properties having a null value. It used to work that way in previous implementation (used in Wicket).

I will not challenge the accuracy of having null values (you probably know better than me) but excluding these null-value properties remains an important use case.

Thanks in advance,
Sebastien.

**Comment by mfursov** [comment]
Could you please paste an example of JSON that is rendered differently in the new and old versions?

**Comment by sebfz1** [comment]
### wicket7.x

```javascript
jQuery('#chart2').kendoChart({ "categoryAxis": { field: 'category' }, "legend": { position: 'top' }, "series": [{"field":"value1","name":"series 1","type":"line"},{"field":"value2","name":"series 2","type":"line"}], "tooltip": { visible: true, template: '#= series.name #: #= kendo.toString(value, "n0") #' }, "title": { text: 'Sample Line Chart' }, "dataSource": window.chart2_datasource });
```

### wicket8.x (openjson)

```javascript
jQuery('#chart2').kendoChart({ "categoryAxis": { field: 'category' }, "legend": { position: 'top' }, "series": [{"axis":null,"color":null,"field":"value1","name":"series 1","stack":null,"tooltip":null,"type":"line"},{"axis":null,"color":null,"field":"value2","name":"series 2","stack":null,"tooltip":null,"type":"line"}], "tooltip": { visible: true, template: '#= series.name #: #= kendo.toString(value, "n0") #' }, "title": { text: 'Sample Line Chart' }, "dataSource": window.chart2_datasource });
```

As you can see, in the wicket8.x, `null` values appear in the json.  
In my use case, this overrides the default values and causes the widget to not work.

**Comment by solomax** [comment]
Would it be OK If additional Stringer will be created?
So you should use JSONObject.toString(new NoNullsStringer())

**Comment by solomax** [comment]
Additional method(s) `pair(String key, Object value)` should be added to Stringer in this case

**Comment by solomax** [comment]
Or maybe better `entry(Map.Entry<String, Object> e)`

**Comment by mfursov** [comment]
I would keep both
- Original behavior (remove nulls from default toString)
- A custom Stringer or a method (like toJSONString()) that keeps nulls as is.

**Comment by sebfz1** [comment]
Sounds perfect to me!

**Comment by solomax** [comment]
@mfursov nulls should be stripped by default?

**Comment by mfursov** [comment]
@solomax if in Wicket 7 or in org.json this behavior was default for years why not have it by default too?
Pros: no runtime bugs in existing code
Cons: toString() does not provide 1:1 invariant for wrap(), but who said it should?

**Comment by solomax** [comment]
@mfursov should I extend my b5595cd commit to implement that? Or I can revert it and create fix for 'vanilla' 1.0.2

**Comment by mfursov** [comment]
@solomax it would be great if you could provide the fix. 

We can release v1.0.3 as soon as we have this fix that makes us compatible with Wicket 7 and original org.json.

**Comment by solomax** [comment]
Would appreciate if someone can test/review new version

**Comment by solomax** [comment]
With this commit should work as expected
Please test/review

**Comment by bitstorm** [comment]
Looks good to me!

**Comment by mfursov** [comment]
Looks like we still will have incompatibilities with org.json in case if we use collections/maps as nulls:
The modified test below fails with org.json (Wicket 7):
```java
    @Test
    public void testToStringWithNulls() throws JSONException {
        JSONObject obj = new JSONObject();
        obj.put("a", "A String")
                .put("n", 666)
                .put("null", (Map)null)
                .put("o", new JSONObject()
                        .put("b", "B String")
                        .put("null", (Collection)null)
                        .put("bool", false));
        assertEquals("{\"a\":\"A String\",\"n\":666,\"o\":{\"b\":\"B String\",\"bool\":false}}", obj.toString());
```

It makes impossible for us to be 100% compatible with org.json in 'toString' method.

**Comment by solomax** [comment]
What is the difference?

**Comment by mfursov** [comment]
```
org.junit.ComparisonFailure: 
Expected :{"a":"A String","n":666,"o":{"b":"B String","bool":false}}
Actual   :{"a":"A String","null":{},"n":666,"o":{"b":"B String","null":[],"bool":false}}
```

**Comment by mfursov** [comment]
org.json does not generate null fields only for Object/Boolean.../String but does generate for Maps and Collections.

**Comment by solomax** [comment]
I see, what would be the conclusion? Should we continue improving? Or is it OK to leave it as is?

**Comment by mfursov** [comment]
I believe we should vote here.

I would say that the old solution (v1.0.2) is a correct API: it has no hidden magic. 
The new solution we have is only 'partially' compatible with legacy code and we have no option to make it 100% compatible.

The ideal case looks like a complete removal of toString() method and asking anyone who migrate to this library to fix issues during compile time. But this is impossible, because toString is an Object's method.

So I vote now for the following solution:
1) Keep toString() correct and simple (output nulls if JSON has nulls)
2) Add extra boolean parameter to JSONStringer to enable mode which will strip nulls. So we will have a solution for those who do not  want to see nulls.
3) Create a wiki page that states all moments where we are incompatible with org.json and shows ways to solve these problems.

In this case I could do item 3. @solomax could privide 1 & 2. 

What do you think?

**Comment by solomax** [comment]
Actually I would vote against `extra boolean parameter`, I would create additional Stringer with only one overridden method ....

**Comment by bitstorm** [comment]
If I had to choose I would go for the last solution suggested by @solomax

**Comment by sebfz1** [comment]
I would personaly have prefered the opposite: the default stringer does
exclude nulls and another stringer to keep nulls...This would avoid silent
api breaks...

**Comment by mfursov** [comment]
I'm OK with another JSONStringer impl. We can even show it in docs as example only, and do not include it into the code.

About nulls:
Please note, that we will have silent API break in any case:  'openjson exclude nulls' behavior will not be the same as 'org.json exclude nulls' for maps and collections.  

If we enable 'exclude nulls' by default we solve the compatibility issue partially only and inherit 'magic' behavior. In this case there will be 3 versions of toString(): org.json, Android and openjson.

@solomax  which  solution would you select?

**Comment by solomax** [comment]
Since @sebfz1 needs "no nulls stringer" I would set this as default and document differences
We can make similar output, but it will require changes in `JSONObject.put`, and I believe this is not necessary, WDYT?

**Comment by bitstorm** [comment]
Sorry, can you elaborate 

> We can make similar output, but it will require changes in JSONObject.put, and I believe this is not necessary
?

I don't understand what you mean with "make similar output". Probably I've missed something.

**Comment by solomax** [comment]
As @mfursov states above, org.json produces different output on null Map, and Collection:
```
org.junit.ComparisonFailure: 
Expected :{"a":"A String","n":666,"o":{"b":"B String","bool":false}}
Actual   :{"a":"A String","null":{},"n":666,"o":{"b":"B String","null":[],"bool":false}}
```
I believe we can get similar output in case `JSONObject.put` will be changed to create empty object/array in `put(Map)`/`put(Collection)`
But I believe it's not that important ....

**Comment by bitstorm** [comment]
@solomax thank you for the clarification. I agree with your proposal.

**Comment by mfursov** [comment]
Ok guys, lets follow the way Max used in the last patch: do not output any nulls in toString and document this behavior. Anyone who want see nulls in toString should use custom Stringer.

@solomax, could you please commit the final patch so I can release 1.0.3?

**Comment by solomax** [comment]
Everything is commited :)

**Comment by mfursov** [comment]
@solomax I would not include any additional dependencies (slf4j) to the package just to log unexpected errors. If the error should never happen - lets just rethrow the exception.

**Comment by solomax** [comment]
toString should be "fail safe" re-throw is not good idea .....

WBR, Maxim
(from mobile, sorry for the typos)

**Comment by mfursov** [comment]
What is org.json behavior in this case? I believe even System.err is better than having dependency on 3rd party library.

**Comment by martin-g** [comment]
@mfursov Why you are against using a logging library ?
slf4j-api is just a facade. Any sane application should already use logging, so I don't see this as a big change. If the application doesn't provide SLF4J impl then it could either use a bridge or not provide anything, in this case SLF4J just logs a single error at the start of the app.
Re-throwing is also a good idea!
`System.err` is not.

**Comment by mfursov** [comment]
@martin-g I have multiple reasons:

1) I believe that openjson should freeze soon and have almost no updates. However other libraries that use it will evolve, including slf4j itself. So we will have runtime conflict resolution when different libraries depends on different versions. The chance that we will have real issue with slf4j is small, not not zero.

2) You never know how this package can be used: I worked on Android projects where we tried to use SLF4J to get simple logger syntax and had very hard application load/startup time limits on slow devices. We had to do perform very specific optimizations to the process of active logger class resolution in SLF4J in order to remove it's impact on startup performance.  The general recommendation from our performance team was: if you need performance: do not use this library at all.

A good solution I believe is to be compatible with org.json (return null) and provide a comment for the method that describes how to convert JSON object to string and be able to handle all kind of errors: use stringer directly.

**Comment by martin-g** [comment]
Thanks, @mfursov !
I see your point now!

But I also don't feel comfortable if any of the libraries in my application silently returns me a random result, like `null` or any other.

@solomax Now the question is to you :-) Why you don't like the idea of (re-)throwing [runtime] exceptions ?

**Comment by solomax** [comment]
I believe throwing from toString/equals/hashcode is not very good idea, these methods might be used in logs and throwing in such places is extremely unexpectable

I personally have no objections on additional small library
I would vote against System.err

**Comment by mfursov** [comment]
@martin-g we lived many years with org.json's behavior that return null silently. Noone was even aware about this behavior and for those who was there was a simple workaround: use stringer directly.

@solomax slf4j is not just a small library. This library is bigger than openjson, adds first dependency to openjson and was added absolutely with no discussion to be used on 1 place in openjson.

**Comment by martin-g** [comment]
> we lived many years with org.json's behavior that return null silently

Then it is OK :-)

**Comment by mfursov** [comment]
Actually I believe that @solomax change is a good change if to consider openjson code as a part of larger library: for example if it was a part of Wicket. In this case the only change is adding a useful log statement.

But when you design an independent library: extra dependencies should be avoided as much as possible and in this context the same change looks different.

For example sl4j team develops new version: 1.8 to be compatible with Java9 modules. I have no idea if migration to Java 9 will bring any changes to functional interface and until openjson does not depend on this library I should not even care about this change.

**Comment by martin-g** [comment]
I totally understand you but knowing that there is /dev/null in a library
makes me nervous.

What about using JUL?
It's part of the JRE already.

On Apr 11, 2017 5:57 PM, "Mikhail Fursov" <notifications@github.com> wrote:

Actually I believe that @solomax <https://github.com/solomax> change is a
good change if to consider openjson code as a part of larger library: for
example if it was a part of Wicket. In this case the only change is adding
a useful log statement.

But when you design an independent library: extra dependencies should be
avoided as much as possible and in this context the same change looks
different.

For example sl4j team develops new version: 1.8 to be compatible with Java9
modules. I have no idea if migration to Java 9 will bring any changes to
functional interface and until openjson does not depend on this library I
should not even care about this change.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjson/openjson/issues/7#issuecomment-293290552>, or mute
the thread

**Comment by mfursov** [comment]
@martin-g if you care about Wicket - just never call toString method. It's anyway 'cursed' by conventional 'skip nulls' behavior. So I would call stringer directly in my app and got exception if serialization failed.

If you care about about other apps that uses openjson: it has the same behavior as it was before with org.json and they also have an option to use stringer directly. All we need is adding a comment to toString method to show the better way of serialization.

**Comment by martin-g** [comment]
:+1:
